// <auto-generated />
using System;
using HealthifyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthifyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HealthifyAPI.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DoencasPreexistentes")
                        .HasColumnType("longtext");

                    b.Property<string>("NivelAtividade")
                        .HasColumnType("longtext");

                    b.Property<string>("Objetivo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PreferenciasAlimentares")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConsultaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConsultaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NutricionistaId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Nutricionista", b =>
                {
                    b.Property<int>("NutricionistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NutricionistaId"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NutricionistaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Nutricionistas");
                });

            modelBuilder.Entity("HealthifyAPI.Models.PlanoAlimentar", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomePlano")
                        .HasColumnType("longtext");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.HasKey("PlanoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NutricionistaId");

                    b.ToTable("PlanosAlimentares");
                });

            modelBuilder.Entity("HealthifyAPI.Models.PlanoReceita", b =>
                {
                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePorcao")
                        .HasColumnType("int");

                    b.HasKey("PlanoId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("PlanoReceitas");
                });

            modelBuilder.Entity("HealthifyAPI.Models.ProgressoCliente", b =>
                {
                    b.Property<int>("ProgressoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("IMC")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Medidas")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProgressoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ProgressoCliente");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<decimal?>("CaloriasPorPorcao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoReceita")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredientes")
                        .HasColumnType("longtext");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("ReceitaId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoUsuario")
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Cliente", b =>
                {
                    b.HasOne("HealthifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Consulta", b =>
                {
                    b.HasOne("HealthifyAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyAPI.Models.Nutricionista", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("HealthifyAPI.Models.Nutricionista", b =>
                {
                    b.HasOne("HealthifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HealthifyAPI.Models.PlanoAlimentar", b =>
                {
                    b.HasOne("HealthifyAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyAPI.Models.Nutricionista", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("HealthifyAPI.Models.PlanoReceita", b =>
                {
                    b.HasOne("HealthifyAPI.Models.PlanoAlimentar", "PlanoAlimentar")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyAPI.Models.Receita", "Receita")
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoAlimentar");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("HealthifyAPI.Models.ProgressoCliente", b =>
                {
                    b.HasOne("HealthifyAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
